name: frontend

on: [push]

defaults:
  run:
    working-directory: frontend
jobs:
  build-storybook:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - run: npm install
      - run: make build-storybook
      - uses: actions/upload-artifact@v2
        with:
          name: storybook
          path: storybook-static/
